# Generated by Django 3.2.11 on 2022-03-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_itemcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('img', models.ImageField(upload_to='product')),
                ('price', models.IntegerField()),
                ('offerprice', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='categ',
        ),
    ]
