# Generated by Django 3.2.11 on 2022-03-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220324_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
