# Generated by Django 3.2.11 on 2022-03-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
