# Generated by Django 3.2.11 on 2022-03-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_products_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='details',
            field=models.TextField(default='update please', max_length=500),
        ),
    ]
